name: Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**/*.py'
      - 'tests/**'
      - 'requirements.txt'
      - '.github/workflows/testing.yml'
      - 'README.md'
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**/*.py'
      - 'tests/**'
      - 'requirements.txt'
      - '.github/workflows/testing.yml'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install system packages (ffmpeg/OpenCV runtime)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libgl1 libglib2.0-0 libsm6 libxext6

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Filter out GPU-only dependencies (cupy) for CPU-based CI
          grep -v "cupy" requirements.txt > requirements-ci.txt
          pip install -r requirements-ci.txt

      - name: Run tests
        run: |
          pytest -q
